import AcademicLayout from "@/components/AcademicLayout";

const License = () => (
  <AcademicLayout>
    <h2>License</h2>

    <div className="notice-box">
      <strong>Important Notice:</strong> LithoMap is released under the GNU Affero General Public
      License, Version 3 (AGPLv3). Use of this software is restricted to non-commercial
      research and educational purposes only. Any use of LithoMap in published research,
      clinical reports, or academic work requires mandatory citation as specified on the{" "}
      <a href="/citation">Citation</a> page.
    </div>

    <div className="section-divider" />

    <h3>Non-Commercial Research Use Only</h3>
    <p>
      This software is provided for non-commercial research and educational purposes only.
      Commercial use, including but not limited to integration into commercial products,
      use in fee-for-service laboratory analyses, or redistribution for profit, is strictly
      prohibited without prior written permission from the authors.
    </p>

    <h3>Mandatory Citation Requirement</h3>
    <p>
      Any publication, report, thesis, or presentation that makes use of LithoMap or
      data generated by LithoMap must include a citation to the original publication.
      See the <a href="/citation">Citation</a> page for the required citation format.
    </p>

    <div className="section-divider" />

    <h3>GNU Affero General Public License, Version 3</h3>

    <div className="license-text">
      <p>GNU AFFERO GENERAL PUBLIC LICENSE</p>
      <p>Version 3, 19 November 2007</p>
      <br />
      <p>Copyright (C) 2007 Free Software Foundation, Inc. &lt;https://fsf.org/&gt;</p>
      <p>Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.</p>
      <br />
      <p><strong>Preamble</strong></p>
      <br />
      <p>
        The GNU Affero General Public License is a free, copyleft license for software and other
        kinds of works, specifically designed to ensure cooperation with the community in the case
        of network server software.
      </p>
      <br />
      <p>
        The licenses for most software and other practical works are designed to take away your
        freedom to share and change the works. By contrast, our General Public Licenses are
        intended to guarantee your freedom to share and change all versions of a program — to
        make sure it remains free software for all its users.
      </p>
      <br />
      <p>
        When we speak of free software, we are referring to freedom, not price. Our General Public
        Licenses are designed to make sure that you have the freedom to distribute copies of free
        software (and charge for them if you wish), that you receive source code or can get it if
        you want it, that you can change the software or use pieces of it in new free programs,
        and that you know you can do these things.
      </p>
      <br />
      <p>
        Developers that use our General Public Licenses protect your rights with two steps:
        (1) assert copyright on the software, and (2) offer you this License which gives you
        legal permission to copy, distribute and/or modify the software.
      </p>
      <br />
      <p>
        A secondary benefit of defending all users' freedoms is that improvements made in
        alternate versions of the program, if they receive widespread use, become available for
        other developers to incorporate. Many developers of free software are heartened and
        encouraged by the resulting cooperation. However, in the case of software used on network
        servers, this result may fail to come about. The GNU General Public License permits making
        a modified version and letting the public access it on a server without ever releasing its
        source code to the public.
      </p>
      <br />
      <p>
        The GNU Affero General Public License is designed specifically to ensure that, in such
        cases, the modified source code becomes available to the community. It requires the
        operator of a network server to provide the source code of the modified version running
        there to the users of that server. Therefore, public use of a modified version, on a
        publicly accessible server, gives the public access to the source code of the modified
        version.
      </p>
      <br />
      <p style={{ fontStyle: "italic", color: "#888" }}>
        [Full license text continues. The complete AGPLv3 license text is available at{" "}
        <a href="https://www.gnu.org/licenses/agpl-3.0.en.html" target="_blank" rel="noopener noreferrer">
          https://www.gnu.org/licenses/agpl-3.0.en.html
        </a>]
      </p>
    </div>

    <p className="last-updated">
      Last updated: 15 February 2026
    </p>
  </AcademicLayout>
);

export default License;
